In [7]:
import pandas as pd
df = pd.read_excel("seoul_cafe_0219.xlsx")
df

,상호명,지점명,도로명주소,층정보,경도,위도,시군구코드,시군구명
0,부동산임대김은숙,NaN,서울특별시 종로구 삼청로 122-1,NaN,126.981840,37.586250,11110,종로구
1,한옥,NaN,서울특별시 종로구 인사동12길 9,1,126.984797,37.574601,11110,종로구
2,상록,NaN,서울특별시 종로구 종로17길 52,NaN,126.988556,37.572430,11110,종로구
3,우궁옛날전통찻집,NaN,서울특별시 종로구 인사동4길 9,NaN,126.986654,37.573231,11110,종로구
4,화동커피,NaN,서울특별시 종로구 율곡로3길 82,NaN,126.982271,37.579313,11110,종로구
...,...,...,...,...,...,...,...,...
23336,주희스커피,NaN,서울특별시 서대문구 통일로 414,NaN,126.947058,37.586483,11410,서대문구
23337,인듀어런스커피,NaN,서울특별시 강남구 선릉로112길 21-4,NaN,127.045435,37.511856,11680,강남구
23338,커피차이,NaN,서울특별시 광진구 뚝섬로56길 14-1,NaN,127.082453,37.530676,11215,광진구
23339,스트라스커피,NaN,서울특별시 구로구 디지털로31길 12,NaN,124.848488,33.474969,11530,구로구
23340,바리스파티움,NaN,서울특별시 송파구 잠실로 62,NaN,127.090289,37.508019,11710,송파구